# Generated by Django 4.1.7 on 2023-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=100)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("api_key", models.CharField(blank=True, max_length=100, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "platform_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hubspot", "hubspot"),
                            ("salesforce", "salesforce"),
                            ("pipedrive", "pipedrive"),
                        ],
                        default="hubspot",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
